### ISSUE TITLE
There is no mapping Defined for the method

### ISSUE THREAD

**Issue by NageshJoy** [springer-opensource/omelet#26]
If I miss to map any of test method in mapping.xml, after executing test, in console I can only see the below error log like "[ERROR] omelet.exception.FrameworkException: There is no mapping Defined for the method" , but  error log not specified which method i have missed to map in mapping.xml

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.16:test (default-test) on project BMCTest: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.16:test failed: There was an error in the forked process
[ERROR] omelet.exception.FrameworkException: There is no mapping Defined for the method
[ERROR] at omelet.data.RefineMappedData.getRefinedClientEnvironment(RefineMappedData.java:89)
[ERROR] at omelet.data.RefineMappedData.getMethodData(RefineMappedData.java:44)
[ERROR] at omelet.data.MethodContext.updateXml(MethodContext.java:247)
[ERROR] at omelet.data.MethodContext.prepareData(MethodContext.java:301)

**Comment by kapilag** [comment]
Yes this is a issue will be fixed , thanks

**Comment by kapilag** [comment]
Fixed , with the new pull 
Thanks govind:)
